# Generated by Django 5.1.4 on 2025-01-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_commands', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='propertyrating',
            table=None,
        ),
        migrations.AlterModelTable(
            name='summary',
            table=None,
        ),
    ]
